# Generated by Django 3.2.15 on 2022-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/noimgg.jpg', upload_to='images/'),
        ),
    ]
